# Generated by Django 5.2.16 on 2026-10-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_todo_subtasks_activity_goal_profile_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='focus_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
