# Generated by Django 5.2.16 on 2026-10-07 02:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_budget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='repeat',
            field=models.CharField(default='NONE', max_length=8),
        ),
        migrations.CreateModel(
            name='Recurring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(default='EXPENSE', max_length=10)),
                ('category', models.CharField(default='BILLS', max_length=20)),
                ('payment_method', models.CharField(default='UPI', max_length=10)),
                ('frequency', models.CharField(default='MONTHLY', max_length=10)),
                ('next_date', models.DateField(default=datetime.date.today)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
