# Generated by Django 5.2.16 on 2026-10-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_habit_weekly_target_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitlog',
            name='frozen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='freeze_month',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='freezes',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
