# Generated by Django 5.2.16 on 2026-10-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_habitlog_frozen_profile_freeze_month_profile_freezes'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
